general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 10
builtin_box_drawing = true 

[window]
startup_mode = "Windowed"
decorations = "Full"
title = "The Scroll of Doom"
opacity = 0.97
padding.x = 12
padding.y = 12


[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[cursor]
style = { shape = "Beam", blinking = "On"}
vi_mode_style = {shape = "Beam", blinking = "On"}
unfocused_hollow = true
thickness = 0.15
blink_timeout = 0

[mouse]
hide_when_typing = true


[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]
